<?php
// $Id$

/**
 * @file
 * CCK Field to integrate products to nodes
 *
 * Allow products to be associated with a content type and added to cart on node creation, provides for editing nodes
 */


// Load additional functions
require_once 'uc_product_content.cck.inc';
require_once 'uc_product_content.ubercart.inc';

/**
 * Implementation of hook_init().
 */
function uc_product_content_init() {
  drupal_add_css(drupal_get_path('module', 'uc_product_content') .'/css/uc-product-content.css');
}

/**
* Implementation of hook_theme().
*/
function uc_product_content_theme() {
  return array_merge(
    _ucpc_cck_themes(),
    _ucpc_ubercart_themes(),
    array()
  );
}

/**
 * Implementation of hook_nodeapi()
 */
function uc_product_content_nodeapi(&$node, $op, $a3 = NULL, $a4 = NULL) {
  switch ($op) {
    case 'load':
      $record = db_fetch_object(db_query("SELECT * FROM {uc_product_content_node_order} WHERE nid = %d", $node->nid));
      if($record != null) {
        $node->order_id = $record->order_id;
        $node->order = uc_order_load($node->order_id);
      }      
      break;
      
    case 'update':
      // update if not new revision
    case 'insert':    
      // we only need to do this once, it will only ever be one order assocated with this node
      $data['nid']      = $node->nid;
      $data['order_id'] = (isset($node->order_id)) ? $node->order_id : '';
      
      drupal_write_record('uc_product_content_node_order', $data, 'nid');
      
      // check if we're dealing with product content nodes that haven't checked out yet, if so, step in and goto cart
      //dsm(array('nodeapi_' . $op, $node));
      if (isset($node->has_product_content) && $node->has_product_content && ! isset($node->order_id)) {
        //dsm('I shouldn\'t be here either!', $node->order_id);
        drupal_goto('cart/checkout');
      }
      
      break;
    
    case 'view':
      if ($node->order_id) {
        _ucpc_show_order($node);
      }
      
      break;
    
    case 'delete':
      $record = db_fetch_object(db_query("SELECT * FROM {uc_product_content_node_order} WHERE nid = %d", $node->nid));
      if($record != null) {
        uc_order_delete($record->order_id);
        db_query("DELETE FROM {uc_product_content_node_order} WHERE nid = %d", $node->nid);
      }
      break;
  }
  //dsm(array('nodeapi_' . $op, $node));
}

/**
 * Implementation of hook_form_alter()
 */
function uc_product_content_form_alter(&$form, &$form_state, $form_id) {
  // Alter the cart view form to make it into an overview and direct users back to the node if changes are needed
  if ($form_id == 'uc_cart_view_form') {
    _ucpc_cart_view_form_alter(&$form, &$form_state);
  }
}